name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      shell: bash
      run: |
        if test ${{ matrix.os }} = macos-latest; then
          brew install libxmlsec1 pkg-config
        fi
        uv sync --dev

    - name: Build
      env:
        SECRET_ZIP_PASS: ${{ secrets.SECRET_ZIP_PASS }}
        BUILD_TYPE: test
        BUILD_OS: ${{ matrix.os }}
      run: uv run bash build.sh

    - name: Test
      run: uv run bash tests/test_NOC.sh

    - name: Upload builds
      uses: actions/upload-artifact@v4
      with:
        name: mhroat-${{ matrix.os }}-${{ github.sha }}
        path: dist/*

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
