name: release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      shell: bash
      run: |
        if test ${{ matrix.os }} = macos-latest; then
          brew install libxmlsec1 pkg-config
        fi
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv update -d

    - name: Build
      env:
        SECRET_ZIP_PASS: ${{ secrets.SECRET_ZIP_PASS }}
        BUILD_TYPE: release
        BUILD_OS: ${{ matrix.os }}
      run: pipenv run bash build.sh

    # Just upload as artifacts
    # The Releases action can't take wildcards and anyway it's worth adding the documentation
    - name: Upload builds
      uses: actions/upload-artifact@v4
      with:
        name: mhroat-${{ matrix.os }}-${{ github.sha }}
        path: dist/*

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
